---
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
containerdConfigPatches: 
- |-
  [plugins."io.containerd.grpc.v1.cri".registry.mirrors."registry:${REGISTRY_PORT}"]
    endpoint = ["http://registry:${REGISTRY_PORT}"]
nodes:
- role: control-plane
- role: worker
- role: worker
# kubeadmConfigPatches:
#   - |
#     apiVersion: kubeadm.k8s.io/v1beta2
#     kind: InitConfiguration
#     nodeRegistration:
#       kubeletExtraArgs:
#         node-labels: "ingress-ready=true"
#         authorization-mode: "AlwaysAllow"
#   extraPortMappings:
#   - containerPort: 80
#     hostPort: 80
#     listenAddress: "0.0.0.0"
#   - containerPort: 443
#     hostPort: 443
#     listenAddress: "0.0.0.0"